### ISSUE TITLE
GitHub Workflow fails due to docker action depreciation

### ISSUE THREAD

**Issue by jackfletch** [jackfletch/jackfletch.com-frontend#28]
GitHub Actions workflow `buildAndPublish` fails to download the docker action. The docker action has been depreciated because [docker is in of all build environments by default](https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions).

Simply use the run command to do Docker related things, for example:
```yaml
steps:
  - name: Pull a Docker image
    run: docker pull alpine:latest

  - name: Build a Docker image
    run: docker build -t org/image:latest .

  - name: Push a Docker image
    run: docker push org/image:latest
```
